server:
  port: 8001

spring:
  application:
    name: block-browse-gauss-web
  data:
    mongodb:
#      uri: mongodb://192.168.1.70:27017
#      uri: mongodb://root:Wuy$7879@s-t4n1c89836ddf5d4-pub.mongodb.singapore.rds.aliyuncs.com:3717/
      uri: mongodb://root:Wuyuan_data@192.168.2.23:27017
      database: browse_gauss
#logging:
#  level:
#    #com.listenrobot.common.http.filter.HttpLoggingFilter: DEBUG
#    org.springframework.data.mongodb.core: DEBUG
#ws:
#  port: 12345
#chain:
#  name: gauss
#  url: http://192.168.2.126:4317
#  prefix: gauss
#bech32:
#  prefix: gaussvalcons
#coin:
#  name: ugauss
#  value: http://walletapi.gaussdex.io/gauss-dex-wallet-transaction/outside/txCouple/queryLastDealAmount
#http:
#  gauss_url: http://192.168.2.31:8000
#  usdg_url: http://192.168.2.31:7000
#  fec_url: http://192.168.2.31:8000
#  igpc_url: http://192.168.2.31:7000
#  head: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiLlkI7lj7DnrqHnkIYiLCJjbGllbnQiOiJiYWNrZW5kLW1hbmFnZXIiLCJleHAiOjE2NTIzMzU1MDEsImlhdCI6MTYyMDc5OTUwMX0.g7DDEoOVYFYIqIWXXsJwu3hggQ75zS6cEXcaL0QZZCk