server:
  port: 8001

spring:
  application:
    name: block-browse-usdg-web
  data:
    mongodb:
#      uri: mongodb://root:Wuyuan_data@192.168.2.23:27017
      uri: mongodb://192.168.1.70:27017
      database: browse_usdg
#ws:
#  port: 12345
#chain:
#  name: usdg
#  url: http://192.168.2.126:5317
#  prefix: usdg
#bech32:
#  prefix: usdgvalcons
#coin:
#  name: uusdg
#  value: http://walletapi.gaussdex.io/gauss-dex-wallet-transaction/outside/txCouple/queryLastDealAmount
#http:
#  gauss_url: http://192.168.2.31:8000
#  usdg_url: http://192.168.2.31:7000
#  fec_url: http://192.168.2.31:8000
#  igpc_url: http://192.168.2.31:7000
#  head: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiLlkI7lj7DnrqHnkIYiLCJjbGllbnQiOiJiYWNrZW5kLW1hbmFnZXIiLCJleHAiOjE2NTIzMzU1MDEsImlhdCI6MTYyMDc5OTUwMX0.g7DDEoOVYFYIqIWXXsJwu3hggQ75zS6cEXcaL0QZZCk